apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stoixima-ingress
  namespace: stoixima-prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - stoixima.yourdomain.com
      secretName: stoixima-tls
  rules:
    - host: stoixima.yourdomain.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 5000
          - path: /hubs
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 5000
          - path: /swagger
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
